name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.1
        with:
          maven-version: 3.8.1

      - name: Test
        run: mvn test
